default:
  ENVIRONMENT:
    SECRET_KEY: test_secret_key
    SUPERUSER_API_KEY: superuser_api_key
    DEBUG: 1
    DEBUG_TOOLBAR_ENABLED: 1
    ALLOWED_HOSTS:
      - 127.0.0.1
      - localhost
    CORS_ORIGIN_WHITELIST:
      - http://localhost:3000
  DATABASE:
    ENGINE: django.db.backends.postgresql
    NAME: '@format {env[POSTGRES_DB]}'
    USER: '@format {env[POSTGRES_USER]}'
    PASSWORD: '@format {env[POSTGRES_PASSWORD]}'
    HOST: '@format {env[SQL_HOST]}'
    PORT: '@format {env[SQL_PORT]}'

production:
  dynaconf_merge: true
  ENVIRONMENT:
    SECRET_KEY: ~
    SUPERUSER_API_KEY: ~
    DEBUG: 0
    DEBUG_TOOLBAR_ENABLED: 0
    ALLOWED_HOSTS:
      - .onrender.com
    CORS_ORIGIN_WHITELIST:
      - https://budgetory.onrender.com
  DATABASE:
    ENGINE: django.db.backends.postgresql
    NAME: ~
    USER: ~
    PASSWORD: ~
    HOST: ~
    PORT: ~
